site_name: Euler
site_url: https://euler.xfbs.net
site_description: "Documentation for euler solutions."
site_author: Patrick M. Elsen
copyright: 'Copyright &copy; 2019 Patrick M. Elsen'
repo_name: 'xfbs/euler-doc'
repo_url: 'https://github.com/xfbs/euler-doc'
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'blue'
  logo:
    icon: 'extension'
  feature:
    tabs: true
nav:
  - About:
    - Intro: index.md
    - Problem:
      - Multiples of 3 and 5: problem/001-multiples-of-3-and-5.md
      - Even Fibonacci Numbers: problem/002-even-fibonacci-numbers.md
  - C:
    - Overview: c/overview.md
    - Library:
      - About: c/lib/index.md
      - Collatz: c/lib/collatz.md
      - Math: c/lib/math.md
      - Prime: c/lib/prime.md
      - vec: c/lib/vec.md
      - vec8: c/lib/vec8.md
      - vec16: c/lib/vec16.md
      - vec32: c/lib/vec32.md
      - vec64: c/lib/vec64.md
      - vecp: c/lib/vecp.md
      - sieve: c/lib/sieve.md
      - Modular Arithmetic: c/lib/modular_arithmetic.md
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.js'
  - 'https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js'
  - 'assets/js/katex.js'
extra_css:
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css'
  - 'https://unpkg.com/mermaid@7.1.2/dist/mermaid.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

